sudo: required

env:
  - DOCKER_COMPOSE_VERSION=3.5
  
services:
  - docker

# addons:
#   sauce_connect: true
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
before_script:
  - docker -v
  - docker-compose -f "docker-compose.yml" up --build -d
  - docker-compose -f "sql/docker-compose.yml" up --build -d
  - docker ps -a
  - sleep 15  # wait for MariaDB to start

script:
  - docker-compose -f "docker-compose.yml" up --build -d
  - docker-compose -f "sql/docker-compose.yml" up --build -d
  - docker ps -a
  - sleep 15  # wait for MariaDB to start
  - docker exec -it nginx_express_phpmyadmin sh -c "nc -z -v node_app_test:3000"
  - docker exec -it nginx_express_phpmyadmin sh -c "ping  -c 4 node_phpmyadmin_test"
  - docker exec -it node_app_test sh -c "ping  -c 4 nginx_express_phpmyadmin"
  - docker exec -it node_app_test sh -c "ping  -c 4 node_mariadb_test"
  - docker exec -it node_app_test sh -c "nc -z -v node_mariadb_test 3306"
  - docker logs node_app_test

after_script:
  - docker-compose -f docker-compose.yml down
  - docker-compose -f sql/docker-compose.yml down
